# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "covoiturage"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

flags:
  # Needed for elementary
  require_explicit_package_overrides_for_builtin_materializations: False
  source_freshness_run_project_hooks: True

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{{{ config(...) }}}}` macro.
models:
  covoiturage:
    +dbt-osmosis: "_{model}.yml"
    analytics:
      +schema: "analytics"
    observatoire:
      +schema: "observatoire_stats"
    geo:
      +schema: "geo_stats"
    dashboard:
      +schema: "dashboard_stats"
    fraud:
      +schema: "fraud"
    campaigns_analytics:
      +schema: "campaigns_analytics"
    export:
      +schema: "export"
    metrics:
      +schema: "metrics"
    metabase:
      +schema: "metabase"
    0_raw_zone:
      +schema: "0_raw_zone"

  ## see docs: https://docs.elementary-data.com/
  elementary:
    +schema: "elementary"