#!/bin/bash

# Ecov 1
psql -d idfm -c "\copy (select rpc_id, journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.idfm where operator_id=1 and journey_start_datetime between '2019-09-01T00:00:00Z' and '2019-09-30T23:59:59Z') to STDOUT WITH (FORCE_QUOTE (journey_start_insee, journey_end_insee), delimiter ',', format csv, header);" > ecov_septembre_2019.csv
psql -d idfm -c "\copy (select rpc_id, journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.idfm where operator_id=1 and journey_start_datetime between '2019-10-01T00:00:00Z' and '2019-10-31T23:59:59Z') to STDOUT WITH (FORCE_QUOTE (journey_start_insee, journey_end_insee), delimiter ',', format csv, header);" > ecov_octobre_2019.csv
psql -d idfm -c "\copy (select rpc_id, journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.idfm where operator_id=1 and journey_start_datetime between '2019-11-01T00:00:00Z' and '2019-11-30T23:59:59Z') to STDOUT WITH (FORCE_QUOTE (journey_start_insee, journey_end_insee), delimiter ',', format csv, header);" > ecov_novembre_2019.csv

# karos 4
psql -d idfm -c "\copy (select rpc_id, journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.idfm where operator_id=4 and journey_start_datetime between '2019-06-18T00:00:00Z' and '2019-06-30T23:59:59Z') to STDOUT WITH (FORCE_QUOTE (journey_start_insee, journey_end_insee), delimiter ',', format csv, header);" > karos_juin_2019.csv
psql -d idfm -c "\copy (select rpc_id, journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.idfm where operator_id=4 and journey_start_datetime between '2019-07-01T00:00:00Z' and '2019-07-31T23:59:59Z') to STDOUT WITH (FORCE_QUOTE (journey_start_insee, journey_end_insee), delimiter ',', format csv, header);" > karos_juillet_2019.csv
psql -d idfm -c "\copy (select rpc_id, journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.idfm where operator_id=4 and journey_start_datetime between '2019-08-01T00:00:00Z' and '2019-08-31T23:59:59Z') to STDOUT WITH (FORCE_QUOTE (journey_start_insee, journey_end_insee), delimiter ',', format csv, header);" > karos_aout_2019.csv
psql -d idfm -c "\copy (select rpc_id, journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.idfm where operator_id=4 and journey_start_datetime between '2019-09-01T00:00:00Z' and '2019-09-30T23:59:59Z') to STDOUT WITH (FORCE_QUOTE (journey_start_insee, journey_end_insee), delimiter ',', format csv, header);" > karos_septembre_2019.csv
psql -d idfm -c "\copy (select rpc_id, journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.idfm where operator_id=4 and journey_start_datetime between '2019-10-01T00:00:00Z' and '2019-10-31T23:59:59Z') to STDOUT WITH (FORCE_QUOTE (journey_start_insee, journey_end_insee), delimiter ',', format csv, header);" > karos_octobre_2019.csv
psql -d idfm -c "\copy (select rpc_id, journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.idfm where operator_id=4 and journey_start_datetime between '2019-11-01T00:00:00Z' and '2019-11-30T23:59:59Z') to STDOUT WITH (FORCE_QUOTE (journey_start_insee, journey_end_insee), delimiter ',', format csv, header);" > karos_novembre_2019.csv

# klaxit 3
psql -d idfm -c "\copy (select rpc_id, journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.idfm where operator_id=3 and journey_start_datetime between '2019-05-01T00:00:00Z' and '2019-05-31T23:59:59Z') to STDOUT WITH (FORCE_QUOTE (journey_start_insee, journey_end_insee), delimiter ',', format csv, header);" > klaxit_mai_2019.csv
psql -d idfm -c "\copy (select rpc_id, journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.idfm where operator_id=3 and journey_start_datetime between '2019-06-01T00:00:00Z' and '2019-06-30T23:59:59Z') to STDOUT WITH (FORCE_QUOTE (journey_start_insee, journey_end_insee), delimiter ',', format csv, header);" > klaxit_juin_2019.csv
psql -d idfm -c "\copy (select rpc_id, journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.idfm where operator_id=3 and journey_start_datetime between '2019-07-01T00:00:00Z' and '2019-07-31T23:59:59Z') to STDOUT WITH (FORCE_QUOTE (journey_start_insee, journey_end_insee), delimiter ',', format csv, header);" > klaxit_juillet_2019.csv
psql -d idfm -c "\copy (select rpc_id, journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.idfm where operator_id=3 and journey_start_datetime between '2019-08-01T00:00:00Z' and '2019-08-31T23:59:59Z') to STDOUT WITH (FORCE_QUOTE (journey_start_insee, journey_end_insee), delimiter ',', format csv, header);" > klaxit_aout_2019.csv
psql -d idfm -c "\copy (select rpc_id, journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.idfm where operator_id=3 and journey_start_datetime between '2019-09-01T00:00:00Z' and '2019-09-30T23:59:59Z') to STDOUT WITH (FORCE_QUOTE (journey_start_insee, journey_end_insee), delimiter ',', format csv, header);" > klaxit_septembre_2019.csv
psql -d idfm -c "\copy (select rpc_id, journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.idfm where operator_id=3 and journey_start_datetime between '2019-10-01T00:00:00Z' and '2019-10-31T23:59:59Z') to STDOUT WITH (FORCE_QUOTE (journey_start_insee, journey_end_insee), delimiter ',', format csv, header);" > klaxit_octobre_2019.csv
psql -d idfm -c "\copy (select rpc_id, journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.idfm where operator_id=3 and journey_start_datetime between '2019-11-01T00:00:00Z' and '2019-11-30T23:59:59Z') to STDOUT WITH (FORCE_QUOTE (journey_start_insee, journey_end_insee), delimiter ',', format csv, header);" > klaxit_novembre_2019.csv

# bbl 9
psql -d idfm -c "\copy (select rpc_id, journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.idfm where operator_id=9 and journey_start_datetime between '2019-11-01T00:00:00Z' and '2019-11-30T23:59:59Z') to STDOUT WITH (FORCE_QUOTE (journey_start_insee, journey_end_insee), delimiter ',', format csv, header);" > bbl_novembre_2019.csv

# delete empty files (211 bytes)
find . -name "*.csv" -type f -size 218c -delete

# convert to :vomit: format
#libreoffice --headless --convert-to xlsx *.csv

