#!/bin/bash

# Ecov 1
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='1' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-04-01' and '2019-04-30') to STDOUT delimiter ',' csv header;" > ecov_avril_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='1' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-05-01' and '2019-05-31') to STDOUT delimiter ',' csv header;" > ecov_mai_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='1' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-06-01' and '2019-06-30') to STDOUT delimiter ',' csv header;" > ecov_juin_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='1' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-07-01' and '2019-07-31') to STDOUT delimiter ',' csv header;" > ecov_juillet_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='1' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-08-01' and '2019-08-31') to STDOUT delimiter ',' csv header;" > ecov_aout_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='1' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-09-01' and '2019-09-30') to STDOUT delimiter ',' csv header;" > ecov_septembre_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='1' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-10-01' and '2019-10-31') to STDOUT delimiter ',' csv header;" > ecov_octobre_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='1' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-11-01' and '2019-11-30') to STDOUT delimiter ',' csv header;" > ecov_novembre_2019.csv

# karos 4
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='4' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-04-01' and '2019-04-30') to STDOUT delimiter ',' csv header;" > karos_avril_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='4' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-05-01' and '2019-05-31') to STDOUT delimiter ',' csv header;" > karos_mai_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='4' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-06-01' and '2019-06-30') to STDOUT delimiter ',' csv header;" > karos_juin_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='4' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-07-01' and '2019-07-31') to STDOUT delimiter ',' csv header;" > karos_juillet_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='4' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-08-01' and '2019-08-31') to STDOUT delimiter ',' csv header;" > karos_aout_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='4' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-09-01' and '2019-09-30') to STDOUT delimiter ',' csv header;" > karos_septembre_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='4' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-10-01' and '2019-10-31') to STDOUT delimiter ',' csv header;" > karos_octobre_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='4' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-11-01' and '2019-11-30') to STDOUT delimiter ',' csv header;" > karos_novembre_2019.csv

# klaxit 3
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='3' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-04-01' and '2019-04-30') to STDOUT delimiter ',' csv header;" > klaxit_avril_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='3' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-05-01' and '2019-05-31') to STDOUT delimiter ',' csv header;" > klaxit_mai_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='3' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-06-01' and '2019-06-30') to STDOUT delimiter ',' csv header;" > klaxit_juin_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='3' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-07-01' and '2019-07-31') to STDOUT delimiter ',' csv header;" > klaxit_juillet_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='3' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-08-01' and '2019-08-31') to STDOUT delimiter ',' csv header;" > klaxit_aout_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='3' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-09-01' and '2019-09-30') to STDOUT delimiter ',' csv header;" > klaxit_septembre_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='3' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-10-01' and '2019-10-31') to STDOUT delimiter ',' csv header;" > klaxit_octobre_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='3' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-11-01' and '2019-11-30') to STDOUT delimiter ',' csv header;" > klaxit_novembre_2019.csv

# bbl 9
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='9' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-04-01' and '2019-04-30') to STDOUT delimiter ',' csv header;" > bbl_avril_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='9' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-05-01' and '2019-05-31') to STDOUT delimiter ',' csv header;" > bbl_mai_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='9' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-06-01' and '2019-06-30') to STDOUT delimiter ',' csv header;" > bbl_juin_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='9' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-07-01' and '2019-07-31') to STDOUT delimiter ',' csv header;" > bbl_juillet_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='9' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-08-01' and '2019-08-31') to STDOUT delimiter ',' csv header;" > bbl_aout_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='9' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-09-01' and '2019-09-30') to STDOUT delimiter ',' csv header;" > bbl_septembre_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='9' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-10-01' and '2019-10-31') to STDOUT delimiter ',' csv header;" > bbl_octobre_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='9' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-11-01' and '2019-11-30') to STDOUT delimiter ',' csv header;" > bbl_novembre_2019.csv

# RoulezMalin 13
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='13' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-04-01' and '2019-04-30') to STDOUT delimiter ',' csv header;" > roulezmalin_avril_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='13' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-05-01' and '2019-05-31') to STDOUT delimiter ',' csv header;" > roulezmalin_mai_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='13' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-06-01' and '2019-06-30') to STDOUT delimiter ',' csv header;" > roulezmalin_juin_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='13' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-07-01' and '2019-07-31') to STDOUT delimiter ',' csv header;" > roulezmalin_juillet_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='13' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-08-01' and '2019-08-31') to STDOUT delimiter ',' csv header;" > roulezmalin_aout_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='13' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-09-01' and '2019-09-30') to STDOUT delimiter ',' csv header;" > roulezmalin_septembre_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='13' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-10-01' and '2019-10-31') to STDOUT delimiter ',' csv header;" > roulezmalin_octobre_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='13' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-11-01' and '2019-11-30') to STDOUT delimiter ',' csv header;" > roulezmalin_novembre_2019.csv

# Mobicoop 14
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='14' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-04-01' and '2019-04-30') to STDOUT delimiter ',' csv header;" > mobicoop_avril_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='14' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-05-01' and '2019-05-31') to STDOUT delimiter ',' csv header;" > mobicoop_mai_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='14' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-06-01' and '2019-06-30') to STDOUT delimiter ',' csv header;" > mobicoop_juin_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='14' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-07-01' and '2019-07-31') to STDOUT delimiter ',' csv header;" > mobicoop_juillet_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='14' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-08-01' and '2019-08-31') to STDOUT delimiter ',' csv header;" > mobicoop_aout_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='14' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-09-01' and '2019-09-30') to STDOUT delimiter ',' csv header;" > mobicoop_septembre_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='14' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-10-01' and '2019-10-31') to STDOUT delimiter ',' csv header;" > mobicoop_octobre_2019.csv
psql -d pdc_producti_4816 -c "\copy (select journey_id, trip_id, journey_start_datetime, journey_start_insee, journey_end_datetime, journey_end_insee, journey_distance, journey_duration, driver_card, passenger_card, operator_class, passenger_over_18, passenger_seats from trip.export where operator_id='14' and (start_territory_id=239 or end_territory_id=239) and journey_start_datetime between '2019-11-01' and '2019-11-30') to STDOUT delimiter ',' csv header;" > mobicoop_novembre_2019.csv

