services:

  # exposing ports is needed for integration and e2e tests to run

  dex:
    ports:
     - 8090:8090
     - 5557:5557
    volumes:
     - ./docker/dex/config-e2e.yaml:/etc/dex/config.yaml:ro
  
  api:
    ports:
      - 8080:8080
    environment:
      APP_POSTGRES_URL: postgres://postgres:postgres@postgres:5432/test
      APP_REDIS_URL: redis://redis:6379/1
      APIE2E_API_URL: https://api.covoiturage.test
      APIE2E_AUTH_ACCESSKEY: operator@example.com
      APIE2E_AUTH_SECRETKEY: password
      APIE2E_AUTH_OPERATOR_EMAIL: operator@example.com
      APIE2E_AUTH_OPERATOR_PASSWORD: admin1234
      APIE2E_AUTH_TERRITORY_EMAIL: territory@example.com
      APIE2E_AUTH_TERRITORY_PASSWORD: admin1234
    volumes:
      - ./docker/api/certs:/app/certs:ro
      - ./api:/app/api

  postgres:
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test

  redis:
    ports:
      - 6379:6379

  mailer:
    ports:
      - 1025:1025

  s3:
    ports:
      - 9000:9000

  wait:
    image: busybox:1.33
    environment:
      DOMAIN: ${WAIT_DOMAIN:-api}
      PORT: ${WAIT_PORT:-8080}
    working_dir: /app/api
    command: ['/bin/sh', '-c', 'until nc -zv $$DOMAIN $$PORT -w1; do echo " Waiting for $$DOMAIN..."; sleep 1; done']
    networks:
      - back
