services:
  proxy:
    image: traefik:v2.5
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    command:
      - '--log.level=DEBUG'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.file.directory=/etc/traefik/dynamic'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.web.address=:80'
      - '--providers.docker.network=rpc_back' # <project_name>_<network_name>
    volumes:
      - ./docker/traefik/config.yml:/etc/traefik/dynamic/config.yml
      - ./docker/traefik/certs:/etc/certs
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
    networks:
      back:
      front:
        aliases:
          - api.covoiturage.test
          - app.covoiturage.test
          - mailer.covoiturage.test
          - s3.covoiturage.test
          - download.covoiturage.test
          - local-pdc-export.s3.covoiturage.test

  mailer:
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.mailer.rule=Host(`mailer.covoiturage.test`)'
      - 'traefik.http.routers.mailer.entrypoints=websecure'
      - 'traefik.http.routers.mailer.tls=true'
      - 'traefik.http.services.mailer.loadbalancer.server.port=8025'

  api:
    environment:
      APP_CORS: https://app.covoiturage.test
      APP_API_URL: https://api.covoiturage.test
      APP_APP_URL: https://app.covoiturage.test
      APP_DASHBOARD_URL: https://app.covoiturage.test
      DEX_REDIRECT_URL: https://api.covoiturage.test/auth/callback
    command: ["just", "serve-unsafe"]
    volumes:
      - ./api:/app/api
      - ./tmp:/tmp
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`api.covoiturage.test`)'
      - 'traefik.http.routers.api.entrypoints=websecure'
      - 'traefik.http.routers.api.tls=true'
      - 'traefik.http.routers.api-http.rule=Host(`api.covoiturage.test`)'
      - 'traefik.http.routers.api-http.entrypoints=web'
      - 'traefik.http.services.api.loadbalancer.server.port=8080'

  # dashboard:
  #   expose:
  #     - 4200
  #   labels:
  #     - 'traefik.enable=true'
  #     - 'traefik.http.routers.dashboard-https.tls=true'
  #     - 'traefik.http.routers.dashboard-https.rule=Host(`app.covoiturage.test`)'
  #     - 'traefik.http.routers.dashboard-https.entrypoints=websecure'
  #     - 'traefik.http.services.dashboard.loadbalancer.server.port=4200'

  s3:
    environment:
      MINIO_DOMAIN: s3.covoiturage.test
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.s3.rule=Host(`s3.covoiturage.test`, `local-pdc-export.s3.covoiturage.test`, `download.covoiturage.test`, `cms.s3.covoiturage.test`)'
      - 'traefik.http.routers.s3.entrypoints=websecure'
      - 'traefik.http.routers.s3.tls=true'
      - 'traefik.http.services.s3.loadbalancer.server.port=9000'
