services:
  e2e:
    build:
      dockerfile: ./docker/api/Dockerfile
      context: .
    environment:
      APIE2E_API_URL: https://api.covoiturage.test
      APIE2E_AUTH_ACCESSKEY: admin@example.com
      APIE2E_AUTH_SECRETKEY: password
    working_dir: /app/api/e2e
    command: ["deno", "test", "--allow-net", "--allow-env", "--unsafely-ignore-certificate-errors"]
    networks:
      - front
      - back

  api:
    volumes:
      - ./docker/api/certs:/app/certs:ro

  postgres:
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test

  redis:
    ports:
      - 6379:6379

  mailer:
    ports:
      - 1025:1025

  wait:
    image: busybox:1.33
    environment:
      DOMAIN: ${WAIT_DOMAIN:-api}
      PORT: ${WAIT_PORT:-8080}
    working_dir: /app/api
    command: ['/bin/sh', '-c', 'until nc -zv $$DOMAIN $$PORT -w1; do echo "waiting for $$DOMAIN"; sleep 1; done']
    networks:
      - back
