CREATE SCHEMA IF NOT EXISTS ANOMALY;

CREATE TABLE IF NOT EXISTS ANOMALY.LABELS (
  _ID serial PRIMARY KEY, CREATED_AT timestamp WITH TIME ZONE NOT NULL DEFAULT NOW(), 
  CARPOOL_ID integer NOT NULL REFERENCES CARPOOL.CARPOOLS(_ID), 
  LABEL varchar NOT NULL, 
  OVERLAP_DURATION_RATIO FLOAT(10), 
  CONFLICTING_CARPOOL_ID integer NOT NULL REFERENCES CARPOOL.CARPOOLS(_ID));

 CREATE UNIQUE INDEX
    ON ANOMALY.LABELS (CARPOOL_ID, LABEL);

ALTER TYPE acquisition.acquisition_status_enum ADD VALUE 'anomaly_error';
