CREATE SCHEMA IF NOT EXISTS ANOMALY;

CREATE TABLE IF NOT EXISTS ANOMALY.LABELS (
  _ID serial PRIMARY KEY, 
  CREATED_AT timestamp WITH TIME ZONE NOT NULL DEFAULT NOW(), 
  CARPOOL_ID integer NOT NULL REFERENCES CARPOOL.CARPOOLS(_ID),
  LABEL varchar NOT NULL, 
  CONFLICTING_CARPOOL_ID integer NOT NULL REFERENCES CARPOOL.CARPOOLS(_ID),
  CONFLICTING_OPERATOR_JOURNEY_ID VARCHAR NOT NULL,
  OVERLAP_DURATION_RATIO FLOAT(10)
);

 CREATE UNIQUE INDEX
    ON ANOMALY.LABELS (CARPOOL_ID, LABEL);

ALTER TYPE carpool.carpool_status_enum ADD VALUE 'anomaly_error';
