export const userSchema = {
  $id: 'user',
  type: 'object',
  required: ['email', 'lastname', 'firstname', 'group', 'permissions', 'password'],
  additionalProperties: false,
  properties: {
    email: { macro: 'email' },
    lastname: { macro: 'varchar' },
    firstname: { macro: 'varchar' },
    phone: { macro: 'phone' },
    group: { macro: 'group' },
    role: { macro: 'role' },
    permissions: { macro: 'permissions' },
    password: { macro: 'password' },
    status: {
      type: 'string',
      enum: ['pending', 'invited', 'active', 'blocked'],
      default: 'pending',
    },
    forgotten_token: { macro: 'token', crypt: true },
    forgotten_at: { macro: 'timestamp' },
    last_connected_at: { macro: 'timestamp' },
    operator: { macro: 'objectid' },
    territory: { macro: 'objectid' },
    options: {
      type: 'object',
      default: {},
    },
    created_at: { macro: 'timestamp' },
    updated_at: { macro: 'timestamp' },
    deleted_at: { macro: 'timestamp' },
  },
};
