CREATE TABLE TERRITORY.TERRITORY_GROUP AS WITH TERRITORY_GROUP_ID AS
	(SELECT DISTINCT AU.TERRITORY_ID
		FROM AUTH.USERS AS AU
		WHERE AU.TERRITORY_ID IS NOT NULL)
SELECT TT._ID,
	TT.COMPANY_ID,
	TT.CREATED_AT,
	TT.UPDATED_AT,
	TT.DELETED_AT,
	TT.NAME,
	TT.SHORTNAME,
	TT.CONTACTS,
	TT.ADDRESS
FROM TERRITORY.TERRITORIES AS TT
JOIN TERRITORY_GROUP_ID AS TGID ON TT._ID = TGID.TERRITORY_ID
