export const HEADERS = {

  journeys: {
    main: {
      journey: [
        'operator.nom_commercial',
        'operator_class',
        'passenger.distance',
        'passenger.seats',
        'passenger.start.datetime',
        'passenger.end.datetime',
        'passenger.start.insee',
        'passenger.end.insee',
        'operator_class',
        'chevron',
      ],
      driverPassenger: [
        'start.insee',
        'end.insee',
        'cost',
      ],
    },
    selection: {
      journey: [
        'operator.nom_commercial',
        'passenger.distance',
        'passenger.seats',
        'passenger.start.date',
        'passenger.start.time',
        'passenger.start.insee',
        'passenger.end.insee',
        'operator_class',
      ],
      driver: [
        'validation.rank',
        'start.datetime',
        'end.datetime',
        'start.insee',
        'end.insee',
        'start.lat',
        'start.lng',
        'end.lat',
        'end.lng',
        'traveler_hash',
      ],
      passenger: [
        'over_18',
        'validation.rank',
        'start.datetime',
        'end.datetime',
        'start.insee',
        'end.insee',
        'start.lat',
        'start.lng',
        'end.lat',
        'end.lng',
        'traveler_hash',
      ],
    },
  },
  tokens: {
    main: [
      'name',
      'createdAt',
    ],
  },
  operators: {
    main: [
      '_id',
      'nom_commercial',
      'raison_sociale',
      'company.siren',
      'company.naf_etablissement',
      'company.naf_entreprise',
      'company.nature_juridique',
      'company.cle_nic',
      'company.rna',
      'company.vat_intra',
      'address.street',
      'address.postcode',
      'address.city',
      'address.country',
      'bank.bank_name',
      'bank.client_name',
      'bank.iban',
      'bank.bic',
    ],
    selection: [
      'nom_commercial',
      'raison_sociale',
    ],

  },
};
