ALTER TABLE CEE.CEE_APPLICATION_ERRORS
  DROP CONSTRAINT IF EXISTS cee_application_errors_application_id_fkey;

CREATE TABLE IF NOT EXISTS CEE.CEE_DELETED_APPLICATIONS AS SELECT * FROM CEE.CEE_APPLICATIONS WHERE FALSE;
