export const userSchema = {
  $id: 'user',
  type: 'object',
  required: ['email', 'lastname', 'firstname', 'group', 'permissions', 'password'],
  additionalProperties: false,
  properties: {
    email: { macro: 'email' },
    lastname: { macro: 'varchar' },
    firstname: { macro: 'varchar' },
    phone: { macro: 'phone' },
    group: { macro: 'group' },
    role: { macro: 'role' },
    permissions: { macro: 'permissions' },
    password: { macro: 'password' },
    status: {
      type: 'string',
      enum: ['pending', 'invited', 'active', 'blocked'],
      default: 'pending',
    },
    hasResetPassword: {
      type: 'boolean',
      default: false,
    },
    forgottenReset: { macro: 'token' },
    forgottenToken: { macro: 'token', crypt: true },
    forgottenAt: { macro: 'timestamp' },
    lastConnectedAt: { macro: 'timestamp' },
    operator: { macro: 'objectid' },
    territory: { macro: 'objectid' },
    options: {
      type: 'object',
      default: {},
    },
    createdAt: { macro: 'timestamp' },
    updatedAt: { macro: 'timestamp' },
    deletedAt: { macro: 'timestamp' },
  },
};
