issuer: http://dex:8090
web:
  http: 0.0.0.0:8090
grpc:
  addr: 0.0.0.0:5557

staticClients:
- id: secret
  redirectURIs:
  - http://localhost:8080/auth/callback
  name: pdc
  secret: secret

# local users for testing
# Enable local users
# @doc https://dexidp.io/docs/connectors/local/
enablePasswordDB: true
staticPasswords:
  - email: admin@example.com
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # password
    username: "application:1"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

storage:
  type: sqlite3
  config:
    file: /tmp/dex.db

connectors:

oauth2:
  responseTypes: [ "code" ]
  skipApprovalScreen: true
  alwaysShowLoginScreen: false
  passwordConnector: local # Allow password grants with local users

expiry:
  deviceRequests: "5m"
  signingKeys: "6h"
  idTokens: "5m"
  refreshTokens:
    disableRotation: false
    reuseInterval: "3s"
    validIfNotUsedFor: "2160h"
    absoluteLifetime: "3960h"
