issuer: http://dex:8090
web:
  http: 0.0.0.0:8090
grpc:
  addr: 0.0.0.0:5557

staticClients:
- id: secret
  redirectURIs:
  - https://api.covoiturage.test/auth/callback
  name: pdc
  secret: secret

# local users for testing
# Enable local users
# @doc https://dexidp.io/docs/connectors/local/
enablePasswordDB: true
staticPasswords:
  - email: admin@example.com
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # password
    username: "registry.admin:0"
    userID: "8b846fa9-4e99-44cf-b1a8-ebb4f7b483d3"
  - email: operator@example.com
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # password
    username: "operator.admin:1"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
  - email: territory@example.com
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # password
    username: "territory.admin:1"
    userID: "2b312dfc-c28b-47a1-a671-7406d7692bc1"

storage:
  type: sqlite3
  config:
    file: /tmp/dex.db

connectors:

oauth2:
  responseTypes: [ "code" ]
  skipApprovalScreen: true
  alwaysShowLoginScreen: false
  passwordConnector: local # Allow password grants with local users

expiry:
  deviceRequests: "5m"
  signingKeys: "6h"
  idTokens: "5m"
  refreshTokens:
    disableRotation: false
    reuseInterval: "3s"
    validIfNotUsedFor: "2160h"
    absoluteLifetime: "3960h"
