export const scoringRules: [number, string[]][] = [
  [1, ['datetimeIdentityCollisionCheck']],
  [1, ['datetimeIdentitySequenceCheck']],
  [1, ['endLatitudeCollisionCheck']],
  [1, ['endLongitudeCollisionCheck']],
  [1, ['highSeatCheck']],
  [1, ['startEndLatitudeCollisionCheck']],
  [1, ['startEndLongitudeCollisionCheck']],
  [1, ['startLatitudeCollisionCheck']],
  [1, ['startLongitudeCollisionCheck']],
  [1, ['theoricalDistanceAndDurationCheck']],
  [1, ['tripIdentityEmailCollisionCheck']],
  [1, ['tripIdentityPhoneCollisionCheck']],
  [1, ['tripIdentityTravelpassCollisionCheck']],
  [1, ['tripIdentityUserIdCollisionCheck']],
  [1, ['tripDatetimeInconsistencyCheck']],
  [1, ['tripDriverIdentityInconsistencyCheck']],
  [1, ['startLongitudeCollisionCheck', 'startLatitudeCollisionCheck']],
  [1, ['endLatitudeCollisionCheck', 'endLongitudeCollisionCheck']],
  [1.5, ['theoricalDistanceAndDurationCheck', 'highDurationCheck']],
  [1.5, ['theoricalDistanceAndDurationCheck', 'lowDurationCheck']],
  [1, ['startEndLatitudeCollisionCheck', 'startEndLongitudeCollisionCheck']],
  [1, ['tripIdentityEmailCollisionCheck', 'tripIdentityFullnameCollisionCheck']],
  [
    4,
    [
      'tripIdentityTravelpassCollisionCheck',
      'tripIdentityEmailCollisionCheck',
      'tripIdentityFullnameCollisionCheck',
      'tripIdentityLastnameCollisionCheck',
      'tripIdentityFirstnameCollisionCheck',
      'tripIdentityPhoneCollisionCheck',
    ],
  ],
  [2, ['tripIdentityUserIdCollisionCheck', 'tripIdentityPhoneTruncCollisionCheck']],
  [
    4,
    [
      'tripIdentityUserIdCollisionCheck',
      'tripIdentityEmailCollisionCheck',
      'tripIdentityFullnameCollisionCheck',
      'tripIdentityLastnameCollisionCheck',
      'tripIdentityFirstnameCollisionCheck',
      'tripIdentityPhoneTruncCollisionCheck',
      'tripIdentityTravelpassCollisionCheck',
    ],
  ],
];

export const scoringFallback: [number, string][] = [
  [2, 'datetimeIdentitySequenceCheck'],
  [3, 'endLatitudeCollisionCheck'],
  [3, 'endLongitudeCollisionCheck'],
  [2, 'highDurationCheck'],
  [2, 'highSeatCheck'],
  [2, 'lowDurationCheck'],
  [1, 'startEndLatitudeCollisionCheck'],
  [1, 'startEndLongitudeCollisionCheck'],
  [1, 'startLatitudeCollisionCheck'],
  [1, 'startLongitudeCollisionCheck'],
  [3, 'theoricalDistanceAndDurationCheck'],
  [1, 'tripIdentityEmailCollisionCheck'],
  [1, 'tripIdentityFullnameCollisionCheck'],
  [1, 'tripIdentityLastnameCollisionCheck'],
  [1, 'tripIdentityFirstnameCollisionCheck'],
  [2, 'tripIdentityPhoneCollisionCheck'],
  [2, 'tripIdentityPhoneTruncCollisionCheck'],
  [1, 'tripIdentityTravelpassCollisionCheck'],
  [2, 'tripIdentityUserIdCollisionCheck'],
  [2, 'tripDatetimeInconsistencyCheck'],
];
