name: 'Analysis - Integration test'

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  e2e:
    name: Test integration
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install
        run: yarn install --frozen-lockfile --non-interactive
        working-directory: api
      - name: Build
        run: yarn build:all
        working-directory: api
      - name: Add host entries
        run: |
          sudo echo "127.0.0.1 api.covoiturage.test" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 s3.covoiturage.test" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 download.covoiturage.test" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 local-pdc-export.s3.covoiturage.test" | sudo tee -a /etc/hosts
      - name: Start
        env:
          APP_INSEE_API_KEY: ${{ secrets.APP_INSEE_API_KEY }}
          APP_POSTGRES_URL: postgres://postgres:postgres@postgres:5432/test
        run: ./tool.sh integration
