name: 'Analysis - Integration test'

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  e2e:
    name: Test integration
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Start
        env:
          APP_INSEE_API_KEY: ${{ secrets.APP_INSEE_API_KEY }}
        run: ./tool.sh integration

