name: Deploy API documentation
permissions:
  contents: read
  pull-requests: write
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - chore/add-bump-action
  pull_request:
    branches:
      - main
jobs:
  deploy-doc:
    if: ${{ github.event_name == 'push' }}
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - doc: api
            version: v3.1
            token: BUMP_TOKEN_API
          - doc: api
            version: v3.0
            token: BUMP_TOKEN_API
          - doc: cee
            version: v3.0
            token: BUMP_TOKEN_CEE
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        uses: bump-sh/github-action@v1
        with:
          doc: ${{ matrix.doc }}
          token: ${{ secrets[matrix.token] }}
          file: api/specs/${{ matrix.doc }}-${{ matrix.version }}.yaml
          branch: ${{ matrix.version }}
