name: Deploy attestation
on:
  push:
    branches: [dev]
jobs:
  build-and-deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: attestation/package-lock.json

      - name: Install and Build 🔧
        run: |
          cd attestation
          npm ci
          NODE_OPTIONS=--openssl-legacy-provider npm run build

      - name: Deploy to bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ vars.ATTESTATION_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.BUCKET_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BUCKET_SECRET_KEY }}
          AWS_S3_ENDPOINT: ${{ vars.BUCKET_ENDPOINT }}
          AWS_REGION: ${{ vars.BUCKET_REGION }}
          SOURCE_DIR: 'attestation/dist/attestation'
