name: Deploy Attestation

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy Attestation
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install NodeJS
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # zizmor: ignore[cache-poisoning] v6.4.0
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: app-attestation/package-lock.json

      - name: Install and Build 🔧
        run: |
          cd app-attestation
          npm ci
          NODE_OPTIONS=--openssl-legacy-provider npm run build

      - name: Deploy to bucket
        uses: jakejarvis/s3-sync-action@be0c4ab89158cac4278689ebedd8407dd5f35a83 # zizmor: ignore[archived-uses] v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ vars.ATTESTATION_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.BUCKET_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BUCKET_SECRET_KEY }}
          AWS_S3_ENDPOINT: ${{ vars.BUCKET_ENDPOINT }}
          AWS_REGION: ${{ vars.BUCKET_REGION }}
          SOURCE_DIR: app-attestation/dist/app-attestation
