name: Deploy API documentations
permissions:
  contents: read
  pull-requests: write
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - chore/add-bump-action
  pull_request:
    branches:
      - main
jobs:
  deploy-doc:
    if: ${{ github.event_name == 'push' }}
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - doc: api
            token: ${{ secrets.BUMP_TOKEN_API }}
            file: api/specs/api-v3.1.yaml
            branch: v3.1
          - doc: api
            token: ${{ secrets.BUMP_TOKEN_API }}
            file: api/specs/api-v3.0.yaml
            branch: v3.0
          - doc: cee
            token: ${{ secrets.BUMP_TOKEN_CEE }}
            file: api/specs/cee-v3.0.yaml
            branch: v3.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        uses: bump-sh/github-action@v1
        with:
          doc: ${{ matrix.doc }}
          token: ${{ matrix.token }}
          file: ${{ matrix.file }}
          branch: ${{ matrix.branch }}
