name: "Quality - API"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - name: Run lint
        working-directory: ./api
        # FIXME
        continue-on-error: true
        run: deno lint

  test:
    needs: [lint]
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock') }}
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - uses: taiki-e/install-action@v2
        with:
          tool: just@1.24.0
      - name: Run unit test
        run: just cache && just ci_test_unit
        working-directory: api
        env:
          APP_POSTGRES_URL: postgres://
          APP_REDIS_URL: redis://

  codeql:
    needs: [test]
    name: CodeQL
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: ['javascript']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        config-file: ./.github/codeql/codeql-config.yml

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

  integration:
    needs: [test]
    name: Test integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock') }}

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - uses: taiki-e/install-action@v2
        with:
          tool: just@1.24.0

      - name: Add host entries
        run: | 
          sudo echo "127.0.0.1 api.covoiturage.test" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 s3.covoiturage.test" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 download.covoiturage.test" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 local-pdc-export.s3.covoiturage.test" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 auth.covoiturage.test" | sudo tee -a /etc/hosts

      - name: Run integration tests
        env:
          APP_POSTGRES_URL: postgres://postgres:postgres@localhost:5432/test
          AWS_ACCESS_KEY_ID: minioadmin
          APP_POSTGRES_TIMEOUT: 120000
          AWS_SECRET_ACCESS_KEY: minioadmin
          AWS_ENDPOINT: http://localhost:9000
          AWS_BUCKET_PREFIX: local-pdc
          APP_REDIS_URL: redis://localhost:6379
          INTEGRATION_MAILER_SMTP_HOST: localhost
          APP_CEE_PUBLIC_KEY_PATH: ${{ github.workspace }}/docker/api/certs/publicKey.pem
          APP_CEE_PRIVATE_KEY_PATH: ${{ github.workspace }}/docker/api/certs/privateKey.pem
          APP_MAIL_SMTP_URL: smtp://localhost:1025
          APP_DATAGOUV_URL: null
          APP_DATAGOUV_KEY: null
          APP_JWT_SECRET: null
          APP_SESSION_SECRET: null
          APP_ROUTECACHE_AUTHTOKEN: null
          AWS_REGION: fr-par
          ETL_MIRROR_URL: https://geo-datasets-mirror.s3.fr-par.scw.cloud
          ETL_ARCHIVES_URL: https://geo-datasets-archives.s3.fr-par.scw.cloud
          PRO_CONNECT_CLIENT_ID: ${{ secrets.PRO_CONNECT_CLIENT_ID }}
          PRO_CONNECT_CLIENT_SECRET: ${{ secrets.PRO_CONNECT_CLIENT_SECRET }}
          DEX_CLIENT_ID: secret
          DEX_CLIENT_SECRET: secret
        run: just cache && just ci_test_integration
        working-directory: api

  api-e2e:
    needs: [test]
    name: API e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock') }}

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - uses: taiki-e/install-action@v2
        with:
          tool: just@1.24.0

      - name: Add host entries
        run: |
          echo "127.0.0.1 api.covoiturage.test" | sudo tee -a /etc/hosts
          echo "127.0.0.1 auth.covoiturage.test" | sudo tee -a /etc/hosts
          echo "127.0.0.1 download.covoiturage.test" | sudo tee -a /etc/hosts
          echo "127.0.0.1 local-pdc-export.s3.covoiturage.test" | sudo tee -a /etc/hosts
          echo "127.0.0.1 mailer.covoiturage.test" | sudo tee -a /etc/hosts
          echo "127.0.0.1 s3.covoiturage.test" | sudo tee -a /etc/hosts

      - name: Run API e2e tests
        working-directory: api-e2e
        env:
          APP_POSTGRES_URL: postgres://postgres:postgres@localhost:5432/test
          APIE2E_API_URL: http://api.covoiturage.test
          APIE2E_AUTH_USERNAME: admin@example.com
          APIE2E_AUTH_PASSWORD: password
        run: just ci
